# Generated by Django 5.0.4 on 2024-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_tags_admin_date_time_movie_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.CharField(max_length=100),
        ),
    ]
