# Generated by Django 5.0.4 on 2024-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_history_userprofile_last_seen_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_video',
            field=models.FileField(default='hi', upload_to='movie_videos'),
            preserve_default=False,
        ),
    ]
