# Generated by Django 5.0.4 on 2024-06-27 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_movie_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
