# Generated by Django 5.0.4 on 2024-06-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_admin_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
