# Generated by Django 5.0.4 on 2024-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='no_of_ratings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
