# Generated by Django 5.0.4 on 2024-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_movie_no_of_ratings_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_time',
        ),
    ]
